Repository Differential/willow-creek, pull requests merged in 2019-11, with the labels that each got.

#63 Adds analytics tracking for main navigation events
  packages/WillowCreekApp/src/index.js
Labels: ready-for-review

#62 Fixes the status bar on android landing and home screen
  packages/WillowCreekApp/src/tabs/home/Home.js
  packages/WillowCreekApp/src/ui/LandingScreen/index.js
Labels: ready-for-review

#76 Fixes content tracking typo
  packages/WillowCreekApp/src/content-single/ContentSingle.js
Labels: ready-for-review

#70 Fixes auth BackButton color
  packages/WillowCreekApp/src/theme/theme.js
Labels: Don't Merge, ready-for-review

#84 Prevent null schedules from breaking feed
  packages/apollos-api/src/data/event/index.js
Labels: merge
